### ISSUE TITLE
psutil.NUM_CPUS is deprecated and removed

### ISSUE THREAD

**Issue by aknies72** [air01a/raspadmin#7]
Original code from `raspadmin/modules/status/status.py`
```javascript
    def getNumCpu():
            return psutil.NUM_CPUS
```

Replace the lines with:
```javascript
    def getNumCpu():
            return psutil.cpu_count()
```

Stop and start the service to make the change effective.
`sudo service raspadmin stop`
`sudo service raspadmin start`

**Comment by air01a** [comment]
Thx, updated !
